import type { Metadata } from "next";
import "./globals.css";
import AuthContextProvider from "@/modules/auth_provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body    className="flex flex-col md:flex-row h-full min-h-screen font-sans">
      <AuthContextProvider>
        {children}
      </AuthContextProvider>
      </body>
    </html>
  );
}
